import { useState } from 'react';
import './HotTakeGenerator.css';

interface HotTakeResponse {
  hot_take: string;
  topic: string;
  style: string;
  agent_used: string;
  web_search_used?: boolean;
  news_context?: string;
}

const HotTakeGenerator = () => {
  const [topic, setTopic] = useState('');
  const [style, setStyle] = useState('controversial');
  const [useWebSearch, setUseWebSearch] = useState(false);
  const [maxArticles, setMaxArticles] = useState(3);
  const [loading, setLoading] = useState(false);
  const [hotTake, setHotTake] = useState<HotTakeResponse | null>(null);
  const [error, setError] = useState('');

  const styles = [
    'controversial',
    'sarcastic',
    'optimistic',
    'pessimistic',
    'absurd',
    'analytical',
    'philosophical',
    'witty',
    'contrarian'
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;

    setLoading(true);
    setError('');
    setHotTake(null);

    try {
      const response = await fetch('http://localhost:8000/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          topic: topic.trim(),
          style: style,
          use_web_search: useWebSearch,
          max_articles: maxArticles,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate hot take');
      }

      const data = await response.json();
      setHotTake(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="hot-take-generator">
      <form onSubmit={handleSubmit} className="generator-form">
        <div className="form-group">
          <label htmlFor="topic">Topic:</label>
          <input
            type="text"
            id="topic"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="Enter a topic for your hot take..."
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="style">Style:</label>
          <select
            id="style"
            value={style}
            onChange={(e) => setStyle(e.target.value)}
          >
            {styles.map((s) => (
              <option key={s} value={s}>
                {s.charAt(0).toUpperCase() + s.slice(1)}
              </option>
            ))}
          </select>
        </div>

        <div className="form-group">
          <div className="checkbox-group">
            <input
              type="checkbox"
              id="useWebSearch"
              checked={useWebSearch}
              onChange={(e) => setUseWebSearch(e.target.checked)}
            />
            <label htmlFor="useWebSearch">
              🔍 Include recent news and headlines
            </label>
          </div>
          <p className="help-text">
            When enabled, recent news articles will be included to make your hot take more timely and relevant
          </p>
        </div>

        {useWebSearch && (
          <div className="form-group">
            <label htmlFor="maxArticles">Number of articles to include:</label>
            <select
              id="maxArticles"
              value={maxArticles}
              onChange={(e) => setMaxArticles(Number(e.target.value))}
            >
              <option value={1}>1 article</option>
              <option value={2}>2 articles</option>
              <option value={3}>3 articles</option>
              <option value={5}>5 articles</option>
            </select>
          </div>
        )}

        <button type="submit" disabled={loading || !topic.trim()}>
          {loading ? 'Generating...' : `Generate Hot Take ${useWebSearch ? '📰' : '🔥'}`}
        </button>
      </form>

      {error && (
        <div className="error">
          <p>Error: {error}</p>
        </div>
      )}

      {hotTake && (
        <div className="hot-take-result">
          <h3>Your Hot Take:</h3>
          <blockquote>{hotTake.hot_take}</blockquote>
          <div className="metadata">
            <p><strong>Topic:</strong> {hotTake.topic}</p>
            <p><strong>Style:</strong> {hotTake.style}</p>
            <p><strong>Generated by:</strong> {hotTake.agent_used}</p>
            {hotTake.web_search_used && (
              <p><strong>📰 News-enhanced:</strong> Yes</p>
            )}
          </div>

          {hotTake.news_context && (
            <details className="news-context">
              <summary>📰 News sources used</summary>
              <div className="news-content">
                <pre>{hotTake.news_context}</pre>
              </div>
            </details>
          )}
        </div>
      )}
    </div>
  );
};

export default HotTakeGenerator;