import { useState } from 'react';
import './HotTakeGenerator.css';

interface HotTakeResponse {
  hot_take: string;
  topic: string;
  style: string;
  agent_used: string;
}

const HotTakeGenerator = () => {
  const [topic, setTopic] = useState('');
  const [style, setStyle] = useState('controversial');
  const [loading, setLoading] = useState(false);
  const [hotTake, setHotTake] = useState<HotTakeResponse | null>(null);
  const [error, setError] = useState('');

  const styles = [
    'controversial',
    'sarcastic',
    'optimistic',
    'pessimistic',
    'absurd',
    'analytical',
    'philosophical',
    'witty',
    'contrarian'
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;

    setLoading(true);
    setError('');
    setHotTake(null);

    try {
      const response = await fetch('http://localhost:8000/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          topic: topic.trim(),
          style: style,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate hot take');
      }

      const data = await response.json();
      setHotTake(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="hot-take-generator">
      <form onSubmit={handleSubmit} className="generator-form">
        <div className="form-group">
          <label htmlFor="topic">Topic:</label>
          <input
            type="text"
            id="topic"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="Enter a topic for your hot take..."
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="style">Style:</label>
          <select
            id="style"
            value={style}
            onChange={(e) => setStyle(e.target.value)}
          >
            {styles.map((s) => (
              <option key={s} value={s}>
                {s.charAt(0).toUpperCase() + s.slice(1)}
              </option>
            ))}
          </select>
        </div>

        <button type="submit" disabled={loading || !topic.trim()}>
          {loading ? 'Generating...' : 'Generate Hot Take 🔥'}
        </button>
      </form>

      {error && (
        <div className="error">
          <p>Error: {error}</p>
        </div>
      )}

      {hotTake && (
        <div className="hot-take-result">
          <h3>Your Hot Take:</h3>
          <blockquote>{hotTake.hot_take}</blockquote>
          <div className="metadata">
            <p><strong>Topic:</strong> {hotTake.topic}</p>
            <p><strong>Style:</strong> {hotTake.style}</p>
            <p><strong>Generated by:</strong> {hotTake.agent_used}</p>
          </div>
        </div>
      )}
    </div>
  );
};

export default HotTakeGenerator;