import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import HotTakeGenerator from './HotTakeGenerator';

// Mock fetch globally
global.fetch = vi.fn();

describe('HotTakeGenerator', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders the form with all required fields', () => {
    render(<HotTakeGenerator />);

    expect(screen.getByLabelText(/topic/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/style/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/include recent news and headlines/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /generate hot take/i })).toBeInTheDocument();
  });

  it('has submit button disabled when topic is empty', () => {
    render(<HotTakeGenerator />);

    const submitButton = screen.getByRole('button', { name: /generate hot take/i });
    expect(submitButton).toBeDisabled();
  });

  it('enables submit button when topic is entered', async () => {
    const user = userEvent.setup();
    render(<HotTakeGenerator />);

    const topicInput = screen.getByLabelText(/topic/i);
    const submitButton = screen.getByRole('button', { name: /generate hot take/i });

    await user.type(topicInput, 'AI in education');

    expect(submitButton).not.toBeDisabled();
  });

  it('shows loading state when generating hot take', async () => {
    const user = userEvent.setup();

    // Mock a delayed response
    (global.fetch as ReturnType<typeof vi.fn>).mockImplementationOnce(
      () => new Promise(() => {}) // Never resolves
    );

    render(<HotTakeGenerator />);

    const topicInput = screen.getByLabelText(/topic/i);
    const submitButton = screen.getByRole('button', { name: /generate hot take/i });

    await user.type(topicInput, 'AI in education');
    await user.click(submitButton);

    expect(screen.getByText(/generating\.\.\./i)).toBeInTheDocument();
    expect(submitButton).toBeDisabled();
  });

  it('displays hot take after successful generation', async () => {
    const user = userEvent.setup();
    const mockResponse = {
      hot_take: 'AI will replace all teachers by 2030!',
      topic: 'AI in education',
      style: 'controversial',
      agent_used: 'test-agent',
    };

    (global.fetch as ReturnType<typeof vi.fn>).mockResolvedValueOnce({
      ok: true,
      json: async () => mockResponse,
    });

    render(<HotTakeGenerator />);

    const topicInput = screen.getByLabelText(/topic/i);
    const submitButton = screen.getByRole('button', { name: /generate hot take/i });

    await user.type(topicInput, 'AI in education');
    await user.click(submitButton);

    await waitFor(() => {
      expect(screen.getByText('AI will replace all teachers by 2030!')).toBeInTheDocument();
    });

    // Verify result section is displayed with metadata
    expect(screen.getByRole('heading', { name: /your hot take/i })).toBeInTheDocument();
    expect(screen.getByText(/generated by:/i)).toBeInTheDocument();
    expect(screen.getByText('test-agent')).toBeInTheDocument();
  });

  it('displays error message on failed generation', async () => {
    const user = userEvent.setup();

    (global.fetch as ReturnType<typeof vi.fn>).mockResolvedValueOnce({
      ok: false,
    });

    render(<HotTakeGenerator />);

    const topicInput = screen.getByLabelText(/topic/i);
    const submitButton = screen.getByRole('button', { name: /generate hot take/i });

    await user.type(topicInput, 'AI in education');
    await user.click(submitButton);

    await waitFor(() => {
      expect(screen.getByText(/error:/i)).toBeInTheDocument();
    });
  });

  it('shows news article count selector when web search is enabled', async () => {
    const user = userEvent.setup();
    render(<HotTakeGenerator />);

    const checkbox = screen.getByLabelText(/include recent news and headlines/i);

    // Initially hidden
    expect(screen.queryByLabelText(/number of articles to include/i)).not.toBeInTheDocument();

    // Show after checkbox is checked
    await user.click(checkbox);
    expect(screen.getByLabelText(/number of articles to include/i)).toBeInTheDocument();
  });

  it('changes style when dropdown is selected', async () => {
    const user = userEvent.setup();
    render(<HotTakeGenerator />);

    const styleSelect = screen.getByLabelText(/style/i) as HTMLSelectElement;

    expect(styleSelect.value).toBe('controversial');

    await user.selectOptions(styleSelect, 'sarcastic');

    expect(styleSelect.value).toBe('sarcastic');
  });

  it('sends correct data to API including web search options', async () => {
    const user = userEvent.setup();
    const mockFetch = vi.fn().mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        hot_take: 'Test take',
        topic: 'Test topic',
        style: 'sarcastic',
        agent_used: 'test-agent',
      }),
    });

    global.fetch = mockFetch;

    render(<HotTakeGenerator />);

    const topicInput = screen.getByLabelText(/topic/i);
    const styleSelect = screen.getByLabelText(/style/i);
    const webSearchCheckbox = screen.getByLabelText(/include recent news and headlines/i);
    const submitButton = screen.getByRole('button', { name: /generate hot take/i });

    await user.type(topicInput, 'Testing');
    await user.selectOptions(styleSelect, 'sarcastic');
    await user.click(webSearchCheckbox);

    const maxArticlesSelect = screen.getByLabelText(/number of articles to include/i);
    await user.selectOptions(maxArticlesSelect, '5');

    await user.click(submitButton);

    await waitFor(() => {
      expect(mockFetch).toHaveBeenCalledWith(
        'http://localhost:8000/api/generate',
        expect.objectContaining({
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            topic: 'Testing',
            style: 'sarcastic',
            use_web_search: true,
            max_articles: 5,
          }),
        })
      );
    });
  });

  it('displays news context when available', async () => {
    const user = userEvent.setup();
    const mockResponse = {
      hot_take: 'News-based hot take!',
      topic: 'Current events',
      style: 'analytical',
      agent_used: 'news-agent',
      web_search_used: true,
      news_context: 'Recent news about current events...',
    };

    (global.fetch as ReturnType<typeof vi.fn>).mockResolvedValueOnce({
      ok: true,
      json: async () => mockResponse,
    });

    render(<HotTakeGenerator />);

    const topicInput = screen.getByLabelText(/topic/i);
    const submitButton = screen.getByRole('button', { name: /generate hot take/i });

    await user.type(topicInput, 'Current events');
    await user.click(submitButton);

    await waitFor(() => {
      expect(screen.getByText(/news sources used/i)).toBeInTheDocument();
      expect(screen.getByText(/news-enhanced:/i)).toBeInTheDocument();
    });
  });
});
